export interface FoodItem {
  id: string;
  name: string;
  category: FoodCategory;
  portion: number; // grams per serving
  portionLabel: string; // "1 unidade", "1 xícara", "100g", etc.
  image: string; // URL to image
  calories: number; // kcal per portion
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  fiber: number; // g
  sodium: number; // mg
  sugar: number; // g
  saturatedFat: number; // g
  calcium: number; // mg
  iron: number; // mg
  vitaminC: number; // mg
  vitaminA: number; // mcg RE
  custom?: boolean; // user-added food
}

export type FoodCategory =
  | 'proteinas'
  | 'carboidratos'
  | 'verduras_legumes'
  | 'frutas'
  | 'laticinios'
  | 'gorduras_oleos'
  | 'graos_cereais'
  | 'bebidas'
  | 'suplementos';

export interface NutritionSummary {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sodium: number;
  sugar: number;
  saturatedFat: number;
  calcium: number;
  iron: number;
  vitaminC: number;
  vitaminA: number;
}

export const categoryLabels: Record<FoodCategory, string> = {
  proteinas: 'Proteínas',
  carboidratos: 'Carboidratos',
  verduras_legumes: 'Verduras & Legumes',
  frutas: 'Frutas',
  laticinios: 'Laticínios',
  gorduras_oleos: 'Gorduras & Óleos',
  graos_cereais: 'Grãos & Cereais',
  bebidas: 'Bebidas',
  suplementos: 'Suplementos',
};

// Fallback high-quality Unsplash photo IDs for common foods
const foodImageFallbacks: Record<string, string> = {
  frango: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
  'peito de frango': 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
  arroz: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
  feijão: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
  batata: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
  ovo: 'https://images.unsplash.com/photo-1585551783917-04742f3d5d46?w=400&h=300&fit=crop',
  salmão: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
  banana: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
  maçã: 'https://images.unsplash.com/photo-1560806887-1d2fb0f6bff7?w=400&h=300&fit=crop',
  leite: 'https://images.unsplash.com/photo-1577003832033-e461efb1fcf5?w=400&h=300&fit=crop',
  queijo: 'https://images.unsplash.com/photo-1452894895917-e01dba2d8b8b?w=400&h=300&fit=crop',
  pão: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
  aveia: 'https://images.unsplash.com/photo-1590769033100-9f60a05a9d82?w=400&h=300&fit=crop',
  brócolis: 'https://images.unsplash.com/photo-1590769033100-9f60a05a9d82?w=400&h=300&fit=crop',
  tomate: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400&h=300&fit=crop',
  abacate: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop',
  carne: 'https://images.unsplash.com/photo-1618885472179-5e474019662c?w=400&h=300&fit=crop',
  iogurte: 'https://images.unsplash.com/photo-1488477181946-6b0b327ef854?w=400&h=300&fit=crop',
  mandioca: 'https://images.unsplash.com/photo-1585070526059-e4ebd6e38f27?w=400&h=300&fit=crop',
  milho: 'https://images.unsplash.com/photo-1599599810694-03a7dd4a8b7f?w=400&h=300&fit=crop',
  laranja: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
};

export function getFoodImage(foodName: string): string {
  const normalizedName = foodName.toLowerCase().trim();

  // Check exact matches first
  if (foodImageFallbacks[normalizedName]) {
    return foodImageFallbacks[normalizedName];
  }

  // Check partial matches
  for (const [key, url] of Object.entries(foodImageFallbacks)) {
    if (normalizedName.includes(key) || key.includes(normalizedName.split(' ')[0])) {
      return url;
    }
  }

  // Fallback to Unsplash search
  const encoded = encodeURIComponent(foodName);
  return `https://source.unsplash.com/400x300/?${encoded},food`;
}

export const TACO_DATABASE: FoodItem[] = [
  // PROTEÍNAS (14 items)
  {
    id: 'prot-001',
    name: 'Peito de Frango Cozido',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('frango'),
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 65,
    sugar: 0,
    saturatedFat: 1.0,
    calcium: 15,
    iron: 0.5,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-002',
    name: 'Patinho (Carne Bovina Magra)',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('carne'),
    calories: 180,
    protein: 25.5,
    carbs: 0,
    fat: 8.0,
    fiber: 0,
    sodium: 55,
    sugar: 0,
    saturatedFat: 3.2,
    calcium: 8,
    iron: 2.8,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-003',
    name: 'Ovo Cozido',
    category: 'proteinas',
    portion: 50,
    portionLabel: '1 unidade',
    image: getFoodImage('ovo'),
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sodium: 72,
    sugar: 0,
    saturatedFat: 1.6,
    calcium: 30,
    iron: 1.8,
    vitaminC: 0,
    vitaminA: 160,
  },
  {
    id: 'prot-004',
    name: 'Salmão Cozido',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('salmão'),
    calories: 234,
    protein: 25.4,
    carbs: 0,
    fat: 13.6,
    fiber: 0,
    sodium: 59,
    sugar: 0,
    saturatedFat: 3.1,
    calcium: 12,
    iron: 0.8,
    vitaminC: 0,
    vitaminA: 64,
  },
  {
    id: 'prot-005',
    name: 'Tilápia Cozida',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('tilápia'),
    calories: 128,
    protein: 26.1,
    carbs: 0,
    fat: 1.7,
    fiber: 0,
    sodium: 56,
    sugar: 0,
    saturatedFat: 0.5,
    calcium: 25,
    iron: 0.6,
    vitaminC: 0,
    vitaminA: 48,
  },
  {
    id: 'prot-006',
    name: 'Atum Enlatado',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('atum'),
    calories: 144,
    protein: 29.9,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    sodium: 302,
    sugar: 0,
    saturatedFat: 0.2,
    calcium: 13,
    iron: 1.6,
    vitaminC: 0,
    vitaminA: 12,
  },
  {
    id: 'prot-007',
    name: 'Sardinha',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('sardinha'),
    calories: 208,
    protein: 25.4,
    carbs: 0,
    fat: 11.0,
    fiber: 0,
    sodium: 472,
    sugar: 0,
    saturatedFat: 2.4,
    calcium: 382,
    iron: 4.3,
    vitaminC: 0,
    vitaminA: 65,
  },
  {
    id: 'prot-008',
    name: 'Peito de Peru',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('peru'),
    calories: 155,
    protein: 29.0,
    carbs: 0,
    fat: 3.2,
    fiber: 0,
    sodium: 67,
    sugar: 0,
    saturatedFat: 1.0,
    calcium: 20,
    iron: 1.3,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-009',
    name: 'Camarão Cozido',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('camarão'),
    calories: 99,
    protein: 21.0,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    sodium: 224,
    sugar: 0,
    saturatedFat: 0.1,
    calcium: 52,
    iron: 0.3,
    vitaminC: 0.9,
    vitaminA: 12,
  },
  {
    id: 'prot-010',
    name: 'Carne de Porco (Lombo)',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('carne de porco'),
    calories: 184,
    protein: 27.3,
    carbs: 0,
    fat: 8.0,
    fiber: 0,
    sodium: 65,
    sugar: 0,
    saturatedFat: 2.8,
    calcium: 6,
    iron: 0.9,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-011',
    name: 'Tofu',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('tofu'),
    calories: 76,
    protein: 8.0,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sodium: 8,
    sugar: 0.2,
    saturatedFat: 0.7,
    calcium: 350,
    iron: 5.4,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-012',
    name: 'Ovos de Codorna',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('ovo'),
    calories: 158,
    protein: 13.0,
    carbs: 1.1,
    fat: 11.0,
    fiber: 0,
    sodium: 141,
    sugar: 0,
    saturatedFat: 3.6,
    calcium: 64,
    iron: 3.6,
    vitaminC: 0,
    vitaminA: 238,
  },
  {
    id: 'prot-013',
    name: 'Peito de Frango Grelhado',
    category: 'proteinas',
    portion: 120,
    portionLabel: '1 filé médio',
    image: getFoodImage('frango'),
    calories: 198,
    protein: 37.2,
    carbs: 0,
    fat: 4.3,
    fiber: 0,
    sodium: 78,
    sugar: 0,
    saturatedFat: 1.2,
    calcium: 18,
    iron: 0.6,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'prot-014',
    name: 'Carne Vermelha Magra (Patinho)',
    category: 'proteinas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('carne'),
    calories: 175,
    protein: 26.0,
    carbs: 0,
    fat: 7.5,
    fiber: 0,
    sodium: 60,
    sugar: 0,
    saturatedFat: 3.0,
    calcium: 10,
    iron: 2.6,
    vitaminC: 0,
    vitaminA: 0,
  },

  // CARBOIDRATOS (9 items)
  {
    id: 'carb-001',
    name: 'Arroz Branco Cozido',
    category: 'carboidratos',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('arroz'),
    calories: 195,
    protein: 3.6,
    carbs: 43.3,
    fat: 0.3,
    fiber: 0.4,
    sodium: 2,
    sugar: 0.1,
    saturatedFat: 0.1,
    calcium: 10,
    iron: 0.3,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'carb-002',
    name: 'Arroz Integral Cozido',
    category: 'carboidratos',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('arroz'),
    calories: 172,
    protein: 4.0,
    carbs: 35.5,
    fat: 1.6,
    fiber: 2.7,
    sodium: 5,
    sugar: 0.3,
    saturatedFat: 0.3,
    calcium: 20,
    iron: 0.8,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'carb-003',
    name: 'Batata Doce Cozida',
    category: 'carboidratos',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('batata doce'),
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    sodium: 55,
    sugar: 4.2,
    saturatedFat: 0.0,
    calcium: 30,
    iron: 0.7,
    vitaminC: 2.4,
    vitaminA: 705,
  },
  {
    id: 'carb-004',
    name: 'Batata Inglesa Cozida',
    category: 'carboidratos',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('batata'),
    calories: 77,
    protein: 1.7,
    carbs: 17.3,
    fat: 0.1,
    fiber: 2.0,
    sodium: 6,
    sugar: 0.9,
    saturatedFat: 0.0,
    calcium: 12,
    iron: 0.3,
    vitaminC: 11.4,
    vitaminA: 2,
  },
  {
    id: 'carb-005',
    name: 'Mandioca Cozida',
    category: 'carboidratos',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('mandioca'),
    calories: 155,
    protein: 0.9,
    carbs: 38.0,
    fat: 0.3,
    fiber: 1.0,
    sodium: 15,
    sugar: 1.7,
    saturatedFat: 0.1,
    calcium: 16,
    iron: 0.2,
    vitaminC: 27.2,
    vitaminA: 2,
  },
  {
    id: 'carb-006',
    name: 'Macarrão Integral Cozido',
    category: 'carboidratos',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('macarrão'),
    calories: 124,
    protein: 4.3,
    carbs: 25.0,
    fat: 0.5,
    fiber: 1.8,
    sodium: 1,
    sugar: 0.3,
    saturatedFat: 0.1,
    calcium: 8,
    iron: 1.9,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'carb-007',
    name: 'Pão Francês',
    category: 'carboidratos',
    portion: 50,
    portionLabel: '1 unidade',
    image: getFoodImage('pão'),
    calories: 139,
    protein: 4.7,
    carbs: 26.5,
    fat: 1.5,
    fiber: 1.2,
    sodium: 402,
    sugar: 0.9,
    saturatedFat: 0.4,
    calcium: 145,
    iron: 1.9,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'carb-008',
    name: 'Tapioca',
    category: 'carboidratos',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('tapioca'),
    calories: 360,
    protein: 0.2,
    carbs: 88.8,
    fat: 0.3,
    fiber: 0.7,
    sodium: 34,
    sugar: 0,
    saturatedFat: 0.1,
    calcium: 20,
    iron: 0.5,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'carb-009',
    name: 'Batata Inglesa Assada',
    category: 'carboidratos',
    portion: 150,
    portionLabel: '1 batata média',
    image: getFoodImage('batata'),
    calories: 116,
    protein: 2.5,
    carbs: 26.0,
    fat: 0.1,
    fiber: 3.0,
    sodium: 9,
    sugar: 1.3,
    saturatedFat: 0.0,
    calcium: 18,
    iron: 0.5,
    vitaminC: 17.1,
    vitaminA: 3,
  },

  // VERDURAS & LEGUMES (9 items)
  {
    id: 'vegl-001',
    name: 'Brócolis Cozido',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('brócolis'),
    calories: 34,
    protein: 2.8,
    carbs: 7.2,
    fat: 0.4,
    fiber: 2.4,
    sodium: 64,
    sugar: 1.7,
    saturatedFat: 0.1,
    calcium: 47,
    iron: 0.7,
    vitaminC: 55.0,
    vitaminA: 84,
  },
  {
    id: 'vegl-002',
    name: 'Espinafre Cozido',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('espinafre'),
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sodium: 92,
    sugar: 0.4,
    saturatedFat: 0.1,
    calcium: 99,
    iron: 2.7,
    vitaminC: 8.4,
    vitaminA: 469,
  },
  {
    id: 'vegl-003',
    name: 'Couve Refogada',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('couve'),
    calories: 33,
    protein: 2.2,
    carbs: 5.4,
    fat: 0.7,
    fiber: 1.4,
    sodium: 54,
    sugar: 0.9,
    saturatedFat: 0.1,
    calcium: 65,
    iron: 0.6,
    vitaminC: 48.4,
    vitaminA: 206,
  },
  {
    id: 'vegl-004',
    name: 'Tomate',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('tomate'),
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sodium: 5,
    sugar: 2.6,
    saturatedFat: 0.0,
    calcium: 12,
    iron: 0.3,
    vitaminC: 13.7,
    vitaminA: 42,
  },
  {
    id: 'vegl-005',
    name: 'Cenoura Crua',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('cenoura'),
    calories: 41,
    protein: 0.9,
    carbs: 10.0,
    fat: 0.2,
    fiber: 2.8,
    sodium: 69,
    sugar: 4.7,
    saturatedFat: 0.0,
    calcium: 33,
    iron: 0.3,
    vitaminC: 5.9,
    vitaminA: 835,
  },
  {
    id: 'vegl-006',
    name: 'Abobrinha Cozida',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('abobrinha'),
    calories: 20,
    protein: 1.4,
    carbs: 3.5,
    fat: 0.4,
    fiber: 1.1,
    sodium: 2,
    sugar: 1.4,
    saturatedFat: 0.1,
    calcium: 19,
    iron: 0.4,
    vitaminC: 20.1,
    vitaminA: 25,
  },
  {
    id: 'vegl-007',
    name: 'Pepino',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('pepino'),
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sodium: 2,
    sugar: 1.7,
    saturatedFat: 0.0,
    calcium: 16,
    iron: 0.3,
    vitaminC: 3.2,
    vitaminA: 16,
  },
  {
    id: 'vegl-008',
    name: 'Alface',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('alface'),
    calories: 15,
    protein: 1.2,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    sodium: 28,
    sugar: 0.8,
    saturatedFat: 0.0,
    calcium: 36,
    iron: 0.5,
    vitaminC: 3.7,
    vitaminA: 141,
  },
  {
    id: 'vegl-009',
    name: 'Abóbora Cozida',
    category: 'verduras_legumes',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('abóbora'),
    calories: 26,
    protein: 1.0,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.5,
    sodium: 1,
    sugar: 2.0,
    saturatedFat: 0.0,
    calcium: 17,
    iron: 0.8,
    vitaminC: 9.0,
    vitaminA: 170,
  },

  // FRUTAS (9 items)
  {
    id: 'frut-001',
    name: 'Banana',
    category: 'frutas',
    portion: 100,
    portionLabel: '1 unidade média',
    image: getFoodImage('banana'),
    calories: 89,
    protein: 1.1,
    carbs: 23.0,
    fat: 0.3,
    fiber: 2.6,
    sodium: 1,
    sugar: 12.2,
    saturatedFat: 0.1,
    calcium: 5,
    iron: 0.3,
    vitaminC: 8.7,
    vitaminA: 3,
  },
  {
    id: 'frut-002',
    name: 'Maçã',
    category: 'frutas',
    portion: 100,
    portionLabel: '1 unidade média',
    image: getFoodImage('maçã'),
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    sodium: 1,
    sugar: 10.4,
    saturatedFat: 0.0,
    calcium: 5,
    iron: 0.1,
    vitaminC: 4.6,
    vitaminA: 3,
  },
  {
    id: 'frut-003',
    name: 'Laranja',
    category: 'frutas',
    portion: 100,
    portionLabel: '1 unidade média',
    image: getFoodImage('laranja'),
    calories: 47,
    protein: 0.7,
    carbs: 11.8,
    fat: 0.2,
    fiber: 2.4,
    sodium: 0,
    sugar: 9.3,
    saturatedFat: 0.0,
    calcium: 40,
    iron: 0.1,
    vitaminC: 53.2,
    vitaminA: 11,
  },
  {
    id: 'frut-004',
    name: 'Abacate',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('abacate'),
    calories: 160,
    protein: 2.0,
    carbs: 8.6,
    fat: 14.7,
    fiber: 6.7,
    sodium: 7,
    sugar: 0.7,
    saturatedFat: 2.1,
    calcium: 12,
    iron: 0.5,
    vitaminC: 10.0,
    vitaminA: 7,
  },
  {
    id: 'frut-005',
    name: 'Morango',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('morango'),
    calories: 32,
    protein: 0.8,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    sodium: 2,
    sugar: 4.9,
    saturatedFat: 0.1,
    calcium: 16,
    iron: 0.4,
    vitaminC: 58.8,
    vitaminA: 1,
  },
  {
    id: 'frut-006',
    name: 'Manga',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('manga'),
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    fiber: 1.6,
    sodium: 2,
    sugar: 13.5,
    saturatedFat: 0.1,
    calcium: 11,
    iron: 0.2,
    vitaminC: 36.4,
    vitaminA: 54,
  },
  {
    id: 'frut-007',
    name: 'Mamão',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('mamão'),
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    fiber: 1.8,
    sodium: 8,
    sugar: 7.6,
    saturatedFat: 0.1,
    calcium: 20,
    iron: 0.1,
    vitaminC: 61.8,
    vitaminA: 47,
  },
  {
    id: 'frut-008',
    name: 'Melancia',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('melancia'),
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sodium: 1,
    sugar: 6.2,
    saturatedFat: 0.1,
    calcium: 7,
    iron: 0.2,
    vitaminC: 8.1,
    vitaminA: 28,
  },
  {
    id: 'frut-009',
    name: 'Uva',
    category: 'frutas',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('uva'),
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    sodium: 2,
    sugar: 15.5,
    saturatedFat: 0.1,
    calcium: 10,
    iron: 0.4,
    vitaminC: 3.2,
    vitaminA: 3,
  },

  // LATICÍNIOS (6 items)
  {
    id: 'latc-001',
    name: 'Leite Integral',
    category: 'laticinios',
    portion: 200,
    portionLabel: '1 xícara',
    image: getFoodImage('leite'),
    calories: 148,
    protein: 6.6,
    carbs: 9.8,
    fat: 8.0,
    fiber: 0,
    sodium: 154,
    sugar: 9.8,
    saturatedFat: 5.0,
    calcium: 238,
    iron: 0.1,
    vitaminC: 0,
    vitaminA: 68,
  },
  {
    id: 'latc-002',
    name: 'Iogurte Natural',
    category: 'laticinios',
    portion: 150,
    portionLabel: '1 pote',
    image: getFoodImage('iogurte'),
    calories: 103,
    protein: 8.4,
    carbs: 7.6,
    fat: 3.6,
    fiber: 0,
    sodium: 140,
    sugar: 6.9,
    saturatedFat: 2.3,
    calcium: 296,
    iron: 0.1,
    vitaminC: 0.5,
    vitaminA: 36,
  },
  {
    id: 'latc-003',
    name: 'Queijo Minas Fresco',
    category: 'laticinios',
    portion: 50,
    portionLabel: '50g',
    image: getFoodImage('queijo'),
    calories: 109,
    protein: 12.6,
    carbs: 0.4,
    fat: 6.0,
    fiber: 0,
    sodium: 198,
    sugar: 0,
    saturatedFat: 3.8,
    calcium: 285,
    iron: 0.1,
    vitaminC: 0,
    vitaminA: 56,
  },
  {
    id: 'latc-004',
    name: 'Queijo Cottage',
    category: 'laticinios',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('queijo'),
    calories: 98,
    protein: 11.0,
    carbs: 4.3,
    fat: 4.3,
    fiber: 0,
    sodium: 388,
    sugar: 2.5,
    saturatedFat: 2.6,
    calcium: 108,
    iron: 0.3,
    vitaminC: 0,
    vitaminA: 48,
  },
  {
    id: 'latc-005',
    name: 'Ricota',
    category: 'laticinios',
    portion: 100,
    portionLabel: '100g',
    image: getFoodImage('ricota'),
    calories: 74,
    protein: 12.3,
    carbs: 1.3,
    fat: 2.2,
    fiber: 0,
    sodium: 207,
    sugar: 0.3,
    saturatedFat: 1.4,
    calcium: 207,
    iron: 0.2,
    vitaminC: 0,
    vitaminA: 32,
  },
  {
    id: 'latc-006',
    name: 'Leite Desnatado',
    category: 'laticinios',
    portion: 200,
    portionLabel: '1 xícara',
    image: getFoodImage('leite'),
    calories: 68,
    protein: 6.8,
    carbs: 10.0,
    fat: 0.2,
    fiber: 0,
    sodium: 158,
    sugar: 10.0,
    saturatedFat: 0.1,
    calcium: 246,
    iron: 0.1,
    vitaminC: 0,
    vitaminA: 9,
  },

  // GORDURAS & ÓLEOS (5 items)
  {
    id: 'gord-001',
    name: 'Azeite de Oliva',
    category: 'gorduras_oleos',
    portion: 14,
    portionLabel: '1 colher de sopa',
    image: getFoodImage('azeite'),
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    fiber: 0,
    sodium: 0,
    sugar: 0,
    saturatedFat: 1.9,
    calcium: 0,
    iron: 0,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'gord-002',
    name: 'Óleo de Coco',
    category: 'gorduras_oleos',
    portion: 14,
    portionLabel: '1 colher de sopa',
    image: getFoodImage('óleo de coco'),
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    fiber: 0,
    sodium: 0,
    sugar: 0,
    saturatedFat: 11.8,
    calcium: 0,
    iron: 0,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'gord-003',
    name: 'Pasta de Amendoim',
    category: 'gorduras_oleos',
    portion: 32,
    portionLabel: '2 colheres de sopa',
    image: getFoodImage('pasta de amendoim'),
    calories: 188,
    protein: 7.0,
    carbs: 6.5,
    fat: 16.0,
    fiber: 1.6,
    sodium: 156,
    sugar: 1.9,
    saturatedFat: 3.1,
    calcium: 42,
    iron: 0.6,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'gord-004',
    name: 'Castanha do Pará',
    category: 'gorduras_oleos',
    portion: 28,
    portionLabel: '28g (1 oz)',
    image: getFoodImage('castanha'),
    calories: 187,
    protein: 4.1,
    carbs: 3.3,
    fat: 18.8,
    fiber: 2.3,
    sodium: 3,
    sugar: 1.3,
    saturatedFat: 4.6,
    calcium: 160,
    iron: 2.4,
    vitaminC: 0.6,
    vitaminA: 0,
  },
  {
    id: 'gord-005',
    name: 'Amêndoa',
    category: 'gorduras_oleos',
    portion: 28,
    portionLabel: '28g (1 oz)',
    image: getFoodImage('amêndoa'),
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.4,
    fiber: 3.5,
    sodium: 0,
    sugar: 1.2,
    saturatedFat: 1.1,
    calcium: 264,
    iron: 1.3,
    vitaminC: 0,
    vitaminA: 0,
  },

  // GRÃOS & CEREAIS (5 items)
  {
    id: 'grao-001',
    name: 'Aveia em Flocos',
    category: 'graos_cereais',
    portion: 40,
    portionLabel: '1/2 xícara',
    image: getFoodImage('aveia'),
    calories: 150,
    protein: 5.0,
    carbs: 27.3,
    fat: 2.7,
    fiber: 4.0,
    sodium: 1,
    sugar: 0.8,
    saturatedFat: 0.5,
    calcium: 27,
    iron: 2.4,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'grao-002',
    name: 'Feijão Preto Cozido',
    category: 'graos_cereais',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('feijão'),
    calories: 227,
    protein: 15.2,
    carbs: 40.8,
    fat: 0.9,
    fiber: 9.0,
    sodium: 4,
    sugar: 0.7,
    saturatedFat: 0.2,
    calcium: 46,
    iron: 3.6,
    vitaminC: 0.4,
    vitaminA: 10,
  },
  {
    id: 'grao-003',
    name: 'Lentilha Cozida',
    category: 'graos_cereais',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('lentilha'),
    calories: 230,
    protein: 17.9,
    carbs: 39.9,
    fat: 0.8,
    fiber: 7.8,
    sodium: 4,
    sugar: 1.6,
    saturatedFat: 0.1,
    calcium: 38,
    iron: 6.6,
    vitaminC: 1.5,
    vitaminA: 22,
  },
  {
    id: 'grao-004',
    name: 'Grão de Bico Cozido',
    category: 'graos_cereais',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('grão de bico'),
    calories: 269,
    protein: 14.5,
    carbs: 44.9,
    fat: 4.3,
    fiber: 7.6,
    sodium: 11,
    sugar: 7.9,
    saturatedFat: 0.4,
    calcium: 80,
    iron: 4.7,
    vitaminC: 2.0,
    vitaminA: 22,
  },
  {
    id: 'grao-005',
    name: 'Quinua Cozida',
    category: 'graos_cereais',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('quinua'),
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.9,
    fiber: 5.2,
    sodium: 13,
    sugar: 1.6,
    saturatedFat: 0.4,
    calcium: 30,
    iron: 2.8,
    vitaminC: 0.1,
    vitaminA: 0,
  },

  // BEBIDAS (3 items)
  {
    id: 'beb-001',
    name: 'Suco Natural de Laranja',
    category: 'bebidas',
    portion: 200,
    portionLabel: '1 copo',
    image: getFoodImage('suco'),
    calories: 86,
    protein: 1.7,
    carbs: 20.3,
    fat: 0.5,
    fiber: 0.4,
    sodium: 2,
    sugar: 17.6,
    saturatedFat: 0.0,
    calcium: 20,
    iron: 0.2,
    vitaminC: 97.0,
    vitaminA: 17,
  },
  {
    id: 'beb-002',
    name: 'Chá Verde',
    category: 'bebidas',
    portion: 240,
    portionLabel: '1 xícara',
    image: getFoodImage('chá'),
    calories: 2,
    protein: 0.1,
    carbs: 0.5,
    fat: 0,
    fiber: 0,
    sodium: 2,
    sugar: 0,
    saturatedFat: 0,
    calcium: 2,
    iron: 0,
    vitaminC: 0.3,
    vitaminA: 0,
  },
  {
    id: 'beb-003',
    name: 'Café com Leite',
    category: 'bebidas',
    portion: 150,
    portionLabel: '1 xícara',
    image: getFoodImage('café'),
    calories: 59,
    protein: 2.9,
    carbs: 6.8,
    fat: 1.8,
    fiber: 0,
    sodium: 56,
    sugar: 6.8,
    saturatedFat: 1.1,
    calcium: 106,
    iron: 0.1,
    vitaminC: 0,
    vitaminA: 24,
  },

  // SUPLEMENTOS (3 items)
  {
    id: 'supl-001',
    name: 'Whey Protein (Porção)',
    category: 'suplementos',
    portion: 30,
    portionLabel: '1 scoop',
    image: getFoodImage('whey'),
    calories: 120,
    protein: 24.0,
    carbs: 2.0,
    fat: 1.5,
    fiber: 0,
    sodium: 50,
    sugar: 1.0,
    saturatedFat: 0.5,
    calcium: 120,
    iron: 0.5,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'supl-002',
    name: 'Creatina Monohidratada',
    category: 'suplementos',
    portion: 5,
    portionLabel: '1 colher de chá',
    image: getFoodImage('creatina'),
    calories: 17,
    protein: 4.0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
    saturatedFat: 0,
    calcium: 0,
    iron: 0,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    id: 'supl-003',
    name: 'Albumina',
    category: 'suplementos',
    portion: 30,
    portionLabel: '2 colheres de sopa',
    image: getFoodImage('albumina'),
    calories: 110,
    protein: 26.0,
    carbs: 0.5,
    fat: 0.2,
    fiber: 0,
    sodium: 80,
    sugar: 0,
    saturatedFat: 0.1,
    calcium: 100,
    iron: 0.2,
    vitaminC: 0,
    vitaminA: 0,
  },
];

export function searchFoods(query: string, category?: FoodCategory): FoodItem[] {
  const lowerQuery = query.toLowerCase().trim();

  return TACO_DATABASE.filter((food) => {
    const matchesQuery =
      food.name.toLowerCase().includes(lowerQuery) ||
      food.id.toLowerCase().includes(lowerQuery);

    const matchesCategory = !category || food.category === category;

    return matchesQuery && matchesCategory;
  });
}

export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return TACO_DATABASE.filter((food) => food.category === category);
}

export function calculateMealNutrition(
  foods: { food: FoodItem; quantity: number }[]
): NutritionSummary {
  const summary: NutritionSummary = {
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
    saturatedFat: 0,
    calcium: 0,
    iron: 0,
    vitaminC: 0,
    vitaminA: 0,
  };

  for (const { food, quantity } of foods) {
    const multiplier = quantity / food.portion;

    summary.calories += food.calories * multiplier;
    summary.protein += food.protein * multiplier;
    summary.carbs += food.carbs * multiplier;
    summary.fat += food.fat * multiplier;
    summary.fiber += food.fiber * multiplier;
    summary.sodium += food.sodium * multiplier;
    summary.sugar += food.sugar * multiplier;
    summary.saturatedFat += food.saturatedFat * multiplier;
    summary.calcium += food.calcium * multiplier;
    summary.iron += food.iron * multiplier;
    summary.vitaminC += food.vitaminC * multiplier;
    summary.vitaminA += food.vitaminA * multiplier;
  }

  // Round to 2 decimal places for cleaner output
  Object.keys(summary).forEach((key) => {
    summary[key as keyof NutritionSummary] = Math.round(summary[key as keyof NutritionSummary] * 100) / 100;
  });

  return summary;
}
